name: "Publish items to MicroCMS"
description: "Publish items to MicroCMS"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    - name: Install dependencies
      shell: bash
      run: |
        go run ${{ github.action_path }}/main.go
